version: '3'
services:
  strapi:
    build:
      context: .
      args:
        STRAPI_VERSION: 4.6.1
    command: sh -c "
      npm install &&
      npm run build &&
      npm run start
      "
    container_name: strapi
    image: strapi/strapi:latest
    restart: always
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      APP_KEYS: ${APP_KEYS}
    working_dir: /srv/app
    volumes:
      - ./config:/srv/app/config
      - ./src:/srv/app/src
      - ./package.json:/srv/app/package.json
      - ./yarn.lock:/srv/app/yarn.lock
      - ./public/uploads:/srv/app/public/uploads
    ports:
      - '1337:1337'
